### ISSUE TITLE
Crashes with "SyntaxError: Unexpected strict mode reserved word"

### ISSUE THREAD

**Issue by fnorf** [berlinermorgenpost/cogran#1]
On Archlinux with npm@2.14.1

```
$ git clone https://github.com/berlinermorgenpost/cogran.git
$ cd cogran/
$ npm install
$ ./index.js 

/tmp/cogran/index.js:11
let optimist = require('optimist');
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by chrtze** [comment]
Which node version?

**Comment by fnorf** [comment]
node is v0.10.40

**Comment by fnorf** [comment]
Works fine with v5.9.1 ;)
