### ISSUE TITLE
npm test fails with Uncaught TypeError: Assignment to constant variable

### ISSUE THREAD

**Issue by fnorf** [berlinermorgenpost/cogran#2]
Running the usage examples manually works fine but doing `npm test` fails with:

```

$ npm test

> cogran@1.0.0 test /tmp/cogran
> ./node_modules/mocha/bin/mocha



  aggregation module
    return type
info:    source file: 1709 features
info:    target file: 190 features
      1) "before each" hook
    output data
info:    source file: 1709 features
info:    target file: 190 features
      2) "before each" hook
    error handling
info:    source file: 1709 features
info:    target file: 190 features
      3) "before each" hook


  0 passing (591ms)
  3 failing

  1) aggregation module return type "before each" hook:
     Uncaught TypeError: Assignment to constant variable.
      at lib/aggregate.js:40:17
      at Array.forEach (native)
      at lib/aggregate.js:35:16
      at node_modules/async/lib/async.js:52:16
      at node_modules/async/lib/async.js:361:13
      at node_modules/async/lib/async.js:52:16
      at done (node_modules/async/lib/async.js:246:17)
      at node_modules/async/lib/async.js:44:16
      at node_modules/async/lib/async.js:358:17
      at node_modules/shapefile/index.js:14:5
      at node_modules/shapefile/read.js:27:11
      at notify (node_modules/d3-queue/build/queue.js:95:54)
      at node_modules/d3-queue/build/queue.js:56:29
      at node_modules/graceful-fs/graceful-fs.js:104:5
      at FSReqWrap.oncomplete (fs.js:82:15)

  2) aggregation module output data "before each" hook:
     Uncaught TypeError: Assignment to constant variable.
      at lib/aggregate.js:40:17
      at Array.forEach (native)
      at lib/aggregate.js:35:16
      at node_modules/async/lib/async.js:52:16
      at node_modules/async/lib/async.js:361:13
      at node_modules/async/lib/async.js:52:16
      at done (node_modules/async/lib/async.js:246:17)
      at node_modules/async/lib/async.js:44:16
      at node_modules/async/lib/async.js:358:17
      at node_modules/shapefile/index.js:14:5
      at node_modules/shapefile/read.js:27:11
      at notify (node_modules/d3-queue/build/queue.js:95:54)
      at node_modules/d3-queue/build/queue.js:56:29
      at node_modules/graceful-fs/graceful-fs.js:104:5
      at FSReqWrap.oncomplete (fs.js:82:15)

  3) aggregation module error handling "before each" hook:
     Uncaught TypeError: Assignment to constant variable.
      at lib/aggregate.js:40:17
      at Array.forEach (native)
      at lib/aggregate.js:35:16
      at node_modules/async/lib/async.js:52:16
      at node_modules/async/lib/async.js:361:13
      at node_modules/async/lib/async.js:52:16
      at done (node_modules/async/lib/async.js:246:17)
      at node_modules/async/lib/async.js:44:16
      at node_modules/async/lib/async.js:358:17
      at node_modules/shapefile/index.js:14:5
      at node_modules/shapefile/read.js:27:11
      at notify (node_modules/d3-queue/build/queue.js:95:54)
      at node_modules/d3-queue/build/queue.js:56:29
      at node_modules/graceful-fs/graceful-fs.js:104:5
      at FSReqWrap.oncomplete (fs.js:82:15)



npm ERR! Test failed.  See above for more details.

```

This happens both on my Linux as well as my colleagues' Windows.

**Comment by fnorf** [comment]
This seems fixed. :) The only errors are failing tests now.
